import type { ResourceSchema, JsonSchema } from './schema-reader.js';
import { TypeMapper } from './type-mapper.js';

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

/** Options for {@link CodeGenerator.generate}. */
export interface CodeGeneratorOptions {
  /**
   * L1 class prefix. e.g. `"Htz"` → `HtzNetwork`.
   */
  prefix: string;

  /**
   * Human-readable provider name for JSDoc. e.g. `"Hetzner"`.
   */
  providerName: string;

  /**
   * Name of the generated resource type constant. e.g. `"HetznerResourceType"`.
   */
  resourceTypeConst: string;
}

// ---------------------------------------------------------------------------
// CodeGenerator
// ---------------------------------------------------------------------------

/**
 * Props whose names clash with `ProviderResource` base class members.
 * Maps original prop name → safe member name used on the generated L1 class.
 * The props interface and `renderProperties()` always use the original key.
 */
const RESERVED_PROP_RENAME: Record<string, string> = {
  type: 'resourceType',
  properties: 'resourceProperties',
  resourceOptions: 'resourceOptionsValue',
  logicalId: 'resourceLogicalId',
};

/**
 * Generates a single TypeScript source file from a list of {@link ResourceSchema}s.
 *
 * The generated file contains:
 * 1. Auto-generated header comment
 * 2. Imports: `ProviderResource`, `IResolvable`, `PropertyValue` from `@cdkx-io/core` + `Construct` from `constructs`
 * 3. `ResourceType` constant — all type strings grouped by domain
 * 4. For each resource (grouped by domain):
 *    - Nested interfaces with JSDoc
 *    - Enums with JSDoc
 *    - Props interface
 *    - L1 class extending `ProviderResource`
 */
export class CodeGenerator {
  /**
   * Generates the full TypeScript source string for all resources.
   *
   * @param resources - The resolved resource schemas to generate from.
   * @param opts - Generation options (prefix, providerName, resourceTypeConst).
   */
  public static generate(
    resources: ResourceSchema[],
    opts: CodeGeneratorOptions,
  ): string {
    const lines: string[] = [];

    // 1. Header
    CodeGenerator.emitHeader(lines, opts);

    // 2. Imports
    CodeGenerator.emitImports(lines);

    // 3. ResourceType constant
    CodeGenerator.emitResourceTypeConst(lines, resources, opts);

    // 4. Shared (common) definitions — emitted once before domain sections.
    //    These are named enums/interfaces from cross-file refs (e.g. common.schema.json).
    const sharedDefs = CodeGenerator.collectSharedDefs(resources);
    if (sharedDefs.size > 0) {
      lines.push('');
      lines.push(`// ${'='.repeat(78)}`);
      lines.push('// Common');
      lines.push(`// ${'='.repeat(78)}`);
      lines.push('');
      lines.push('// Shared definitions referenced by multiple resources.');
      for (const [name, def] of sharedDefs) {
        if (def.enum) {
          CodeGenerator.emitEnum(lines, name, def);
        } else if (def.properties || def.type === 'object') {
          // Use empty string for resourceName — shared interfaces have no parent resource.
          CodeGenerator.emitInterface(lines, name, def, '', {});
        }
      }
    }

    // 5. Resources grouped by domain
    const byDomain = CodeGenerator.groupByDomain(resources);
    for (const [domain, domainResources] of Object.entries(byDomain)) {
      lines.push('');
      lines.push(`// ${'='.repeat(78)}`);
      lines.push(`// ${domain}`);
      lines.push(`// ${'='.repeat(78)}`);
      for (const resource of domainResources) {
        CodeGenerator.emitResource(lines, resource, opts, sharedDefs);
      }
    }

    lines.push('');
    return lines.join('\n');
  }

  // ---------------------------------------------------------------------------
  // Private — header & imports
  // ---------------------------------------------------------------------------

  private static emitHeader(lines: string[], opts: CodeGeneratorOptions): void {
    lines.push(
      '// ============================================================',
    );
    lines.push('// AUTO-GENERATED — DO NOT EDIT');
    lines.push('//');
    lines.push(
      `// Generated by spec-to-cdkx from ${opts.providerName} JSON Schema files.`,
    );
    lines.push(
      '// To regenerate: yarn nx run @cdkx-io/' +
        opts.providerName.toLowerCase() +
        ':codegen',
    );
    lines.push(
      '// ============================================================',
    );
  }

  private static emitImports(lines: string[]): void {
    lines.push('');
    lines.push(
      "import { ProviderResource, IResolvable, PropertyValue } from '@cdkx-io/core';",
    );
    lines.push("import { Construct } from 'constructs';");
  }

  // ---------------------------------------------------------------------------
  // Private — ResourceType constant
  // ---------------------------------------------------------------------------

  private static emitResourceTypeConst(
    lines: string[],
    resources: ResourceSchema[],
    opts: CodeGeneratorOptions,
  ): void {
    lines.push('');
    lines.push('/**');
    lines.push(
      ` * All ${opts.providerName} resource type identifiers, grouped by domain.`,
    );
    lines.push(' *');
    lines.push(
      ' * Use these constants when constructing L1 resources to avoid typos.',
    );
    lines.push(' */');
    lines.push(`export const ${opts.resourceTypeConst} = {`);

    const byDomain = CodeGenerator.groupByDomain(resources);
    const domainEntries = Object.entries(byDomain);
    for (let di = 0; di < domainEntries.length; di++) {
      const [domain, domainResources] = domainEntries[di];
      lines.push(`  /** ${domain} resources. */`);
      lines.push(`  ${domain}: {`);
      for (const r of domainResources) {
        lines.push(`    /** \`${r.typeName}\` */`);
        lines.push(`    ${r.resourceName}: '${r.typeName}',`);
      }
      const isLast = di === domainEntries.length - 1;
      lines.push(`  }${isLast ? '' : ','}`);
    }

    lines.push('} as const;');
  }

  // ---------------------------------------------------------------------------
  // Private — per-resource emission
  // ---------------------------------------------------------------------------

  private static emitResource(
    lines: string[],
    resource: ResourceSchema,
    opts: CodeGeneratorOptions,
    sharedDefs: Map<string, JsonSchema>,
  ): void {
    const { resourceName, definitions } = resource;

    // Collect nested interfaces and enums defined in this schema.
    const nestedInterfaces: Array<[string, JsonSchema]> = [];
    const enums: Array<[string, JsonSchema]> = [];

    for (const [name, def] of Object.entries(definitions)) {
      // Only emit definitions that are explicitly defined in THIS schema file.
      if (name.includes('#')) continue; // cross-file keyed entry

      const isLocalDef = CodeGenerator.isDefinedInFile(name, resource);
      if (!isLocalDef) continue;

      // Skip definitions already emitted in the shared Common section.
      if (sharedDefs.has(name)) continue;

      if (def.enum) {
        enums.push([name, def]);
      } else if (def.properties || def.type === 'object') {
        nestedInterfaces.push([name, def]);
      }
    }

    lines.push('');
    lines.push(`// --- ${resourceName} ---`);

    // Nested interfaces
    for (const [name, def] of nestedInterfaces) {
      CodeGenerator.emitInterface(lines, name, def, resourceName, definitions);
    }

    // Enums
    for (const [name, def] of enums) {
      CodeGenerator.emitEnum(lines, name, def);
    }

    // Props interface
    CodeGenerator.emitPropsInterface(
      lines,
      resource,
      opts,
      nestedInterfaces,
      enums,
    );

    // L1 class
    CodeGenerator.emitL1Class(lines, resource, opts);
  }

  // ---------------------------------------------------------------------------
  // Private — nested interfaces
  // ---------------------------------------------------------------------------

  private static emitInterface(
    lines: string[],
    name: string,
    def: JsonSchema,
    _resourceName: string,
    _definitions: Record<string, JsonSchema>,
  ): void {
    if (def.description) {
      lines.push('/**');
      lines.push(` * ${def.description}`);
      lines.push(' */');
    }
    lines.push(`export interface ${name} {`);
    for (const [propName, prop] of Object.entries(def.properties ?? {})) {
      if (prop.description) {
        lines.push('  /**');
        lines.push(`   * ${prop.description}`);
        lines.push('   */');
      }
      const camel = TypeMapper.toCamelCase(propName);
      const tsType = TypeMapper.mapType(prop, { resourceName: name }, camel);
      const required = (def.required ?? []).includes(propName);
      lines.push(`  ${camel}${required ? '' : '?'}: ${tsType};`);
    }
    lines.push('}');
    lines.push('');
  }

  // ---------------------------------------------------------------------------
  // Private — enums
  // ---------------------------------------------------------------------------

  private static emitEnum(
    lines: string[],
    name: string,
    def: JsonSchema,
  ): void {
    if (def.description) {
      lines.push('/**');
      lines.push(` * ${def.description}`);
      lines.push(' */');
    }
    lines.push(`export enum ${name} {`);
    for (const value of def.enum ?? []) {
      const memberName = CodeGenerator.toEnumMemberName(value);
      lines.push(`  /** \`${value}\` */`);
      lines.push(`  ${memberName} = '${value}',`);
    }
    lines.push('}');
    lines.push('');
  }

  // ---------------------------------------------------------------------------
  // Private — props interface
  // ---------------------------------------------------------------------------

  private static emitPropsInterface(
    lines: string[],
    resource: ResourceSchema,
    opts: CodeGeneratorOptions,
    _nestedInterfaces: Array<[string, JsonSchema]>,
    _enums: Array<[string, JsonSchema]>,
  ): void {
    const {
      resourceName,
      description,
      properties,
      required,
    } = resource;
    const interfaceName = `${opts.providerName}${resourceName}`;

    if (description) {
      lines.push('/**');
      lines.push(` * Props for {@link ${opts.prefix}${resourceName}}.`);
      lines.push(' *');
      lines.push(` * ${description}`);
      lines.push(' */');
    }
    lines.push(`export interface ${interfaceName} {`);

    for (const [propName, prop] of Object.entries(properties)) {
      // All properties in the map are user-settable — no skipping needed.
      // readOnlyProperties that are NOT in properties (e.g. API-generated IDs
      // like networkId) never appear in this loop in the first place.

      const camel = TypeMapper.toCamelCase(propName);
      const tsType = TypeMapper.mapType(
        prop,
        { resourceName },
        camel,
        resource.definitions,
      );
      const isRequired = required.includes(propName);

      if (prop.description) {
        lines.push('  /**');
        lines.push(`   * ${prop.description}`);
        lines.push('   */');
      }
      lines.push(`  ${camel}${isRequired ? '' : '?'}: ${tsType};`);
    }

    lines.push('}');
    lines.push('');
  }

  // ---------------------------------------------------------------------------
  // Private — L1 class
  // ---------------------------------------------------------------------------

  private static emitL1Class(
    lines: string[],
    resource: ResourceSchema,
    opts: CodeGeneratorOptions,
  ): void {
    const {
      resourceName,
      typeName,
      description,
      readOnlyProperties,
      properties,
      required,
    } = resource;
    const className = `${opts.prefix}${resourceName}`;
    const propsInterface = `${opts.providerName}${resourceName}`;

    // All properties in the map are writable by the user. readOnlyProperties
    // that are NOT in properties (API-generated IDs) never appear here.
    const writableProps = Object.entries(properties);

    lines.push('/**');
    lines.push(
      ` * L1 construct for a ${opts.providerName} ${resourceName} resource.`,
    );
    if (description) {
      lines.push(' *');
      lines.push(` * ${description}`);
    }
    lines.push(' */');
    lines.push(`export class ${className} extends ProviderResource {`);

    // RESOURCE_TYPE_NAME
    lines.push(
      `  /** The CloudFormation-style type name for this resource. */`,
    );
    lines.push(`  public static readonly RESOURCE_TYPE_NAME = '${typeName}';`);
    lines.push('');

    // attr* members for readOnlyProperties
    for (const attrName of readOnlyProperties) {
      const pascal = TypeMapper.toAttrMemberName(attrName);
      lines.push(`  /**`);
      lines.push(`   * The \`${attrName}\` attribute of this resource.`);
      lines.push(
        `   * Resolves to \`{ ref: logicalId, attr: '${attrName}' }\` at synthesis time.`,
      );
      lines.push(`   */`);
      lines.push(`  public readonly attr${pascal}: IResolvable;`);
    }

    if (readOnlyProperties.length > 0) lines.push('');

    // Public mutable members for each writable prop
    for (const [propName, prop] of writableProps) {
      const camel = TypeMapper.toCamelCase(propName);
      const memberName = RESERVED_PROP_RENAME[camel] ?? camel;
      const tsType = TypeMapper.mapType(
        prop,
        { resourceName },
        camel,
        resource.definitions,
      );
      const isRequired = required.includes(propName);
      lines.push(`  public ${memberName}${isRequired ? '' : '?'}: ${tsType};`);
    }

    if (writableProps.length > 0) lines.push('');

    // Constructor — omit `= {}` default when any props are required
    const hasRequired = required.length > 0;
    const propsArg = hasRequired
      ? `props: ${propsInterface}`
      : `props: ${propsInterface} = {}`;
    lines.push(`  constructor(scope: Construct, id: string, ${propsArg}) {`);
    lines.push(`    super(scope, id, {`);
    lines.push(`      type: ${className}.RESOURCE_TYPE_NAME,`);
    lines.push(`    });`);
    lines.push(`    this.node.defaultChild = this;`);

    // Initialize attr* members
    for (const attrName of readOnlyProperties) {
      const pascal = TypeMapper.toAttrMemberName(attrName);
      lines.push(`    this.attr${pascal} = this.getAtt('${attrName}');`);
    }

    // Assign props to mutable members
    for (const [propName] of writableProps) {
      const camel = TypeMapper.toCamelCase(propName);
      const memberName = RESERVED_PROP_RENAME[camel] ?? camel;
      lines.push(`    this.${memberName} = props.${camel};`);
    }

    lines.push(`  }`);
    lines.push('');

    // renderProperties() override — always use the original prop key as JSON key
    lines.push(
      `  protected override renderProperties(): Record<string, PropertyValue> {`,
    );
    lines.push(`    return {`);
    for (const [propName] of writableProps) {
      const camel = TypeMapper.toCamelCase(propName);
      const memberName = RESERVED_PROP_RENAME[camel] ?? camel;
      lines.push(`      ${camel}: this.${memberName},`);
    }
    lines.push(`    } as unknown as Record<string, PropertyValue>;`);
    lines.push(`  }`);
    lines.push(`}`);
    lines.push('');
  }

  // ---------------------------------------------------------------------------
  // Private — helpers
  // ---------------------------------------------------------------------------

  private static groupByDomain(
    resources: ResourceSchema[],
  ): Record<string, ResourceSchema[]> {
    const map: Record<string, ResourceSchema[]> = {};
    for (const r of resources) {
      if (!map[r.domain]) map[r.domain] = [];
      map[r.domain].push(r);
    }
    return map;
  }

  /**
   * Checks whether `defName` is a definition local to the resource's schema file
   * (not imported from common or another file). Used to decide what to emit.
   */
  private static isDefinedInFile(
    defName: string,
    resource: ResourceSchema,
  ): boolean {
    return resource.localDefinitionNames.includes(defName);
  }

  /**
   * Converts an enum value string to a valid TypeScript enum member name.
   * e.g. `"eu-central"` → `EU_CENTRAL`, `"label_selector"` → `LABEL_SELECTOR`
   */
  private static toEnumMemberName(value: string): string {
    return value
      .replace(/[^a-zA-Z0-9_]/g, '_')
      .replace(/([a-z])([A-Z])/g, '$1_$2')
      .toUpperCase();
  }

  /**
   * Collects all shared definitions referenced across all resources.
   * Returns a `Map<name, JsonSchema>` preserving insertion order (first-seen wins).
   *
   * "Shared" means the definition came from a cross-file ref (e.g. `common.schema.json`)
   * and was identified as a named type (enum or interface) by `SchemaReader`.
   */
  private static collectSharedDefs(
    resources: ResourceSchema[],
  ): Map<string, JsonSchema> {
    const map = new Map<string, JsonSchema>();
    for (const resource of resources) {
      for (const name of resource.sharedDefinitionNames) {
        if (map.has(name)) continue;
        const def = resource.definitions[name];
        if (def) {
          map.set(name, def);
        }
      }
    }
    return map;
  }
}
