import type { ResourceSchema, ApiSpec } from './schema-reader.js';

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

/** Options for {@link RegistryGenerator.generate}. */
export interface RegistryGeneratorOptions {
  /**
   * The name of the resource type constant imported from `resources.generated.ts`.
   * e.g. `"HetznerResourceType"`.
   */
  resourceTypeConst: string;

  /**
   * The import path for the resource type constant.
   * Defaults to `'./resources.generated'`.
   */
  resourcesImportPath?: string;
}

// ---------------------------------------------------------------------------
// RegistryGenerator
// ---------------------------------------------------------------------------

/**
 * Generates a `resource-registry.generated.ts` file from a list of
 * {@link ResourceSchema}s that have an `api` block.
 *
 * The generated file contains:
 * 1. Auto-generated header comment
 * 2. Import of the resource type constant
 * 3. `ResourceConfig` interface (verbatim — same shape as the hand-written file)
 * 4. `asRecord` helper function
 * 5. `RESOURCE_REGISTRY` object — one entry per resource with an `api` block
 */
export class RegistryGenerator {
  /**
   * Generates the full TypeScript source string for the resource registry.
   *
   * @param resources - All resolved resource schemas (only those with `api` are emitted).
   * @param opts - Generation options.
   */
  public static generate(
    resources: ResourceSchema[],
    opts: RegistryGeneratorOptions,
  ): string {
    const importPath = opts.resourcesImportPath ?? './resources.generated';
    const apiResources = resources.filter((r) => r.api !== undefined);

    const lines: string[] = [];

    // 1. Header
    RegistryGenerator.emitHeader(lines);

    // 2. Import — only needed when there are API resources that reference it
    if (apiResources.length > 0) {
      lines.push('');
      lines.push(`import { ${opts.resourceTypeConst} } from '${importPath}';`);
    }

    // 3. ResourceConfig interface
    RegistryGenerator.emitResourceConfigInterface(lines);

    // 4. asRecord helper — only needed when there are API resources that call it
    if (apiResources.length > 0) {
      RegistryGenerator.emitAsRecordHelper(lines);
    }

    // 5. RESOURCE_REGISTRY
    RegistryGenerator.emitRegistry(lines, apiResources, opts.resourceTypeConst);

    lines.push('');
    return lines.join('\n');
  }

  // ---------------------------------------------------------------------------
  // Private — header
  // ---------------------------------------------------------------------------

  private static emitHeader(lines: string[]): void {
    lines.push(
      '// ============================================================',
    );
    lines.push('// AUTO-GENERATED — DO NOT EDIT');
    lines.push('//');
    lines.push('// Generated by spec-to-cdkx from provider JSON Schema files.');
    lines.push('// To regenerate: yarn nx run @cdkx-io/hetzner:codegen');
    lines.push(
      '// ============================================================',
    );
  }

  // ---------------------------------------------------------------------------
  // Private — ResourceConfig interface
  // ---------------------------------------------------------------------------

  private static emitResourceConfigInterface(lines: string[]): void {
    lines.push('');
    lines.push(
      '// ─── Types ───────────────────────────────────────────────────────────────────',
    );
    lines.push('');
    lines.push('/**');
    lines.push(' * Configuration for a single resource type.');
    lines.push(' *');
    lines.push(' * Derived from JSON Schema files — `readOnlyProperties`,');
    lines.push(
      ' * `createOnlyProperties`, `primaryIdentifier`, and the `api` block.',
    );
    lines.push(' */');
    lines.push('export interface ResourceConfig {');
    lines.push('  /**');
    lines.push('   * HTTP path for creating the resource.');
    lines.push(
      '   * For action resources this may contain `{propName}` placeholders.',
    );
    lines.push('   */');
    lines.push('  readonly createPath: string;');
    lines.push('');
    lines.push('  /**');
    lines.push(
      '   * Build the GET path for reading back the resource after creation.',
    );
    lines.push('   * Receives the `physicalId` stored in engine state.');
    lines.push('   * `undefined` for action resources.');
    lines.push('   */');
    lines.push('  readonly getPath?: (physicalId: string) => string;');
    lines.push('');
    lines.push('  /**');
    lines.push('   * Build the PUT path for updating a mutable resource.');
    lines.push(
      '   * `undefined` for fully immutable resources (action resources).',
    );
    lines.push('   */');
    lines.push('  readonly updatePath?: (physicalId: string) => string;');
    lines.push('');
    lines.push('  /**');
    lines.push('   * Build the DELETE path.');
    lines.push(
      '   * For action resources the path is a template string — the adapter',
    );
    lines.push('   * substitutes `{parentIdProp}` before making the request.');
    lines.push('   */');
    lines.push(
      '  readonly deletePath: string | ((physicalId: string) => string);',
    );
    lines.push('');
    lines.push('  /**');
    lines.push(
      '   * Extract the named output attributes from the API create/get response.',
    );
    lines.push(
      '   * Keys must match the `attr` field used in `{ ref, attr }` tokens.',
    );
    lines.push('   */');
    lines.push(
      '  readonly extractOutputs: (response: unknown) => Record<string, unknown>;',
    );
    lines.push('');
    lines.push('  /**');
    lines.push(
      '   * Extract the stable physical ID from the API create response.',
    );
    lines.push('   */');
    lines.push('  readonly extractPhysicalId: (');
    lines.push('    response: unknown,');
    lines.push('    properties: Record<string, unknown>,');
    lines.push('  ) => string;');
    lines.push('');
    lines.push('  /**');
    lines.push(
      '   * Property names (camelCase) that are `createOnlyProperties` in the schema.',
    );
    lines.push('   */');
    lines.push('  readonly createOnlyProps: ReadonlySet<string>;');
    lines.push('');
    lines.push('  /**');
    lines.push(
      '   * Property names to exclude from PUT body in addition to `createOnlyProps`.',
    );
    lines.push('   */');
    lines.push('  readonly updateExcludeProps?: ReadonlySet<string>;');
    lines.push('');
    lines.push('  /**');
    lines.push(
      '   * True for resources managed via parent-resource action endpoints.',
    );
    lines.push('   */');
    lines.push('  readonly isActionResource?: true;');
    lines.push('');
    lines.push('  /**');
    lines.push(
      "   * For action resources: property name holding the parent resource's physical ID.",
    );
    lines.push('   */');
    lines.push('  readonly parentIdProp?: string;');
    lines.push('}');
  }

  // ---------------------------------------------------------------------------
  // Private — asRecord helper
  // ---------------------------------------------------------------------------

  private static emitAsRecordHelper(lines: string[]): void {
    lines.push('');
    lines.push(
      '// ─── Helpers ──────────────────────────────────────────────────────────────────',
    );
    lines.push('');
    lines.push('function asRecord(v: unknown): Record<string, unknown> {');
    lines.push(
      "  if (v !== null && typeof v === 'object' && !Array.isArray(v)) {",
    );
    lines.push('    return v as Record<string, unknown>;');
    lines.push('  }');
    lines.push('  return {};');
    lines.push('}');
  }

  // ---------------------------------------------------------------------------
  // Private — RESOURCE_REGISTRY
  // ---------------------------------------------------------------------------

  private static emitRegistry(
    lines: string[],
    resources: ResourceSchema[],
    resourceTypeConst: string,
  ): void {
    lines.push('');
    lines.push(
      '// ─── Registry ─────────────────────────────────────────────────────────────────',
    );
    lines.push('');
    lines.push('/**');
    lines.push(
      ' * Static registry mapping every resource type to its API config.',
    );
    lines.push(' *');
    lines.push(' * Auto-generated from JSON Schema files.');
    lines.push(' */');
    lines.push(
      `export const RESOURCE_REGISTRY: Record<string, ResourceConfig> = {`,
    );

    for (const resource of resources) {
      RegistryGenerator.emitRegistryEntry(lines, resource, resourceTypeConst);
    }

    lines.push('};');
  }

  private static emitRegistryEntry(
    lines: string[],
    resource: ResourceSchema,
    resourceTypeConst: string,
  ): void {
    const api = resource.api as ApiSpec;
    const isAction = api.responseBodyKey === null;
    const domainParts = resource.typeName.split('::');
    const domain = domainParts[1] ?? '';
    const resourceName = domainParts[2] ?? '';

    lines.push('');
    lines.push(
      `  // ─── ${domain}: ${resourceName} ${'─'.repeat(Math.max(0, 60 - domain.length - resourceName.length))}`,
    );
    lines.push(`  [${resourceTypeConst}.${domain}.${resourceName}]: {`);

    // createPath
    lines.push(`    createPath: '${api.createPath}',`);

    // getPath
    if (api.getPath) {
      lines.push(`    getPath: ${RegistryGenerator.buildPathFn(api.getPath)},`);
    }

    // updatePath
    if (api.updatePath) {
      lines.push(
        `    updatePath: ${RegistryGenerator.buildPathFn(api.updatePath)},`,
      );
    }

    // deletePath — action resources keep as string (adapter substitutes parentId)
    if (isAction) {
      lines.push(`    deletePath: '${api.deletePath}',`);
    } else {
      lines.push(
        `    deletePath: ${RegistryGenerator.buildPathFn(api.deletePath)},`,
      );
    }

    // extractPhysicalId
    RegistryGenerator.emitExtractPhysicalId(lines, resource, api, isAction);

    // extractOutputs
    RegistryGenerator.emitExtractOutputs(lines, resource, api, isAction);

    // createOnlyProps
    const props = resource.createOnlyProperties;
    if (props.length === 0) {
      lines.push(`    createOnlyProps: new Set(),`);
    } else {
      const quoted = props.map((p) => `'${p}'`).join(', ');
      lines.push(`    createOnlyProps: new Set([${quoted}]),`);
    }

    // isActionResource
    if (isAction) {
      lines.push(`    isActionResource: true,`);
    }

    // parentIdProp
    if (isAction && api.compositeIdProps && api.compositeIdProps.length > 0) {
      lines.push(`    parentIdProp: '${api.compositeIdProps[0]}',`);
    }

    lines.push(`  },`);
  }

  /**
   * Converts a path template like `/networks/{id}` to a TypeScript arrow function.
   * Handles arbitrary `{placeholder}` names:
   * - `{id}` → `(id) => \`/networks/${id}\``
   * - `{name}` with `encodeURIComponent` pattern (detected by query string) →
   *   `(name) => \`/ssh_keys?name=${encodeURIComponent(name)}\``
   */
  private static buildPathFn(pathTemplate: string): string {
    // Extract the first placeholder name
    const match = pathTemplate.match(/\{(\w+)\}/);
    if (!match) {
      // No placeholder — static path, return as arrow fn anyway for interface compat
      return `(_id) => '${pathTemplate}'`;
    }
    const paramName = match[1];

    // If the path has a query string with the param (e.g. ?name=...), we need
    // encodeURIComponent for safety (matches hand-written ssh-key behaviour).
    const hasQueryString = pathTemplate.includes('?');
    const converted = pathTemplate.replace(
      `{${paramName}}`,
      hasQueryString
        ? `\${encodeURIComponent(${paramName})}`
        : `\${${paramName}}`,
    );

    return `(${paramName}) => \`${converted}\``;
  }

  private static emitExtractPhysicalId(
    lines: string[],
    resource: ResourceSchema,
    api: ApiSpec,
    isAction: boolean,
  ): void {
    if (isAction) {
      // Composite physical ID from compositeIdProps
      const props = api.compositeIdProps ?? [];
      const parts = props
        .map((p) => `String(properties['${p}'] ?? '')`)
        .join(" + ':' + ");
      lines.push(`    extractPhysicalId: (_response, properties) => ${parts},`);
    } else {
      // Normal resource: String(asRecord(asRecord(response)['bodyKey'])['responseField'])
      const bodyKey = api.responseBodyKey as string;
      const responseField = RegistryGenerator.resolvePhysicalIdResponseField(
        resource,
        api,
      );
      lines.push(`    extractPhysicalId: (response) =>`);
      lines.push(
        `      String(asRecord(asRecord(response)['${bodyKey}'])['${responseField}']),`,
      );
    }
  }

  /**
   * Determines which field in the API response body to use as the physical ID.
   *
   * Priority:
   * 1. If `outputAttrMap` exists, use the value for the first `readOnlyProperty`.
   * 2. Otherwise default to `'id'` (the API always assigns an integer `id`).
   */
  private static resolvePhysicalIdResponseField(
    resource: ResourceSchema,
    api: ApiSpec,
  ): string {
    if (api.outputAttrMap) {
      const firstReadOnly = resource.readOnlyProperties[0];
      if (firstReadOnly && api.outputAttrMap[firstReadOnly] !== undefined) {
        return api.outputAttrMap[firstReadOnly];
      }
    }
    return 'id';
  }

  private static emitExtractOutputs(
    lines: string[],
    resource: ResourceSchema,
    api: ApiSpec,
    isAction: boolean,
  ): void {
    if (isAction) {
      lines.push(`    extractOutputs: () => ({}),`);
      return;
    }

    const bodyKey = api.responseBodyKey as string;
    const readOnly = resource.readOnlyProperties;

    if (readOnly.length === 0) {
      // No read-only outputs to extract.
      lines.push(`    extractOutputs: () => ({}),`);
      return;
    }

    // Build attr→responseField map: prefer explicit outputAttrMap, otherwise
    // fall back to the prop name itself (e.g. primary-ip where `id` maps to `id`).
    const attrMap = api.outputAttrMap ?? {};
    const entries = readOnly.map((prop) => {
      const responseField = attrMap[prop] ?? prop;
      return `      ${prop}: asRecord(asRecord(response)['${bodyKey}'])['${responseField}'],`;
    });

    if (entries.length === 0) {
      lines.push(`    extractOutputs: () => ({}),`);
      return;
    }

    lines.push(`    extractOutputs: (response) => ({`);
    for (const entry of entries) {
      lines.push(entry);
    }
    lines.push(`    }),`);
  }
}
