import type { ResourceSchema } from './schema-reader.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Configuration for a single resource type in the runtime.
 * Used by RuntimeAdapter to extract physical IDs and handle updates.
 */
export interface RuntimeResourceConfig {
  /**
   * The key in the handler's state object that holds the physical ID.
   * For simple resources: the property name from primaryIdentifier (e.g., 'networkId').
   * For composite ID resources: always 'physicalId'.
   */
  readonly physicalIdKey: string;

  /**
   * Property names (camelCase) that are create-only and cannot be updated.
   * Derived from `createOnlyProperties` in the JSON Schema.
   */
  readonly createOnlyProps: ReadonlySet<string>;
}

// ---------------------------------------------------------------------------
// RuntimeConfigGenerator
// ---------------------------------------------------------------------------

/**
 * Generates a `runtime-config.generated.ts` file from ResourceSchemas.
 *
 * The generated file contains a mapping from resource type to runtime
 * configuration. This is auto-generated from JSON Schema files to ensure
 * the runtime configuration stays synchronized with the schema definitions.
 *
 * The physicalIdKey is determined heuristically from primaryIdentifier:
 * - Single-element arrays: use that property name (e.g., 'networkId')
 * - Multi-element arrays: use 'physicalId' (composite ID for action resources)
 */
export class RuntimeConfigGenerator {
  /**
   * Generates the full TypeScript source string for the runtime config.
   *
   * @param resources - All resolved resource schemas.
   * @returns The TypeScript source code.
   */
  public static generate(resources: ResourceSchema[]): string {
    const lines: string[] = [];

    // 1. Header
    RuntimeConfigGenerator.emitHeader(lines);

    // 2. RuntimeResourceConfig interface
    RuntimeConfigGenerator.emitInterface(lines);

    // 3. RUNTIME_CONFIGS constant
    RuntimeConfigGenerator.emitConfigs(lines, resources);

    lines.push('');
    return lines.join('\n');
  }

  // ---------------------------------------------------------------------------
  // Private — header
  // ---------------------------------------------------------------------------

  private static emitHeader(lines: string[]): void {
    lines.push(
      '// ============================================================',
    );
    lines.push('// AUTO-GENERATED — DO NOT EDIT');
    lines.push('//');
    lines.push('// Generated by spec-to-cdkx from provider JSON Schema files.');
    lines.push('// To regenerate: yarn nx run @cdkx-io/hetzner:codegen');
    lines.push(
      '// ============================================================',
    );
  }

  // ---------------------------------------------------------------------------
  // Private — interface
  // ---------------------------------------------------------------------------

  private static emitInterface(lines: string[]): void {
    lines.push('');
    lines.push(
      '// ─── Types ────────────────────────────────────────────────────',
    );
    lines.push('');
    lines.push('/**');
    lines.push(' * Configuration for a single resource type in the runtime.');
    lines.push(' *');
    lines.push(
      ' * Auto-generated from JSON Schema files — `createOnlyProperties`,',
    );
    lines.push(' * `primaryIdentifier`, and `readOnlyProperties`.');
    lines.push(' */');
    lines.push('export interface RuntimeResourceConfig {');
    lines.push('  /**');
    lines.push(
      '   * The key in the handler state object that holds the physical ID.',
    );
    lines.push(
      '   * For simple resources: the property name (e.g., "networkId").',
    );
    lines.push('   * For composite IDs: always "physicalId".');
    lines.push('   */');
    lines.push('  readonly physicalIdKey: string;');
    lines.push('');
    lines.push('  /**');
    lines.push(
      '   * Property names that cannot be updated (createOnlyProperties).',
    );
    lines.push('   */');
    lines.push('  readonly createOnlyProps: ReadonlySet<string>;');
    lines.push('}');
  }

  // ---------------------------------------------------------------------------
  // Private — configs
  // ---------------------------------------------------------------------------

  private static emitConfigs(
    lines: string[],
    resources: ResourceSchema[],
  ): void {
    lines.push('');
    lines.push(
      '// ─── Runtime Configs ────────────────────────────────────────────',
    );
    lines.push('');
    lines.push('/**');
    lines.push(' * Runtime configuration for all resource types.');
    lines.push(' *');
    lines.push(
      ' * Maps resource type strings (e.g., "Hetzner::Networking::Network")',
    );
    lines.push(' * to their runtime configuration.');
    lines.push(' */');
    lines.push(
      'export const RUNTIME_CONFIGS: Record<string, RuntimeResourceConfig> = {',
    );

    for (const resource of resources) {
      RuntimeConfigGenerator.emitConfigEntry(lines, resource);
    }

    lines.push('};');
  }

  private static emitConfigEntry(
    lines: string[],
    resource: ResourceSchema,
  ): void {
    const physicalIdKey = RuntimeConfigGenerator.resolvePhysicalIdKey(resource);
    const createOnlyProps = resource.createOnlyProperties ?? [];

    lines.push('');
    lines.push(`  // ${resource.typeName}`);
    lines.push(`  '${resource.typeName}': {`);
    lines.push(`    physicalIdKey: '${physicalIdKey}',`);

    if (createOnlyProps.length === 0) {
      lines.push(`    createOnlyProps: new Set(),`);
    } else {
      const quoted = createOnlyProps.map((p) => `'${p}'`).join(', ');
      lines.push(`    createOnlyProps: new Set([${quoted}]),`);
    }

    lines.push(`  },`);
  }

  // ---------------------------------------------------------------------------
  // Private — resolve physicalIdKey
  // ---------------------------------------------------------------------------

  /**
   * Resolves the physicalIdKey from primaryIdentifier.
   *
   * Logic:
   * - Single-element primaryIdentifier: use the property name
   *   (e.g., ["/properties/networkId"] → "networkId")
   * - Multi-element primaryIdentifier: use "physicalId"
   *   (composite ID for action resources like subnets)
   *
   * @param resource - The resource schema.
   * @returns The physicalIdKey to use.
   */
  private static resolvePhysicalIdKey(resource: ResourceSchema): string {
    const primaryId = resource.primaryIdentifier ?? [];

    if (primaryId.length === 0) {
      // Fallback: no primary identifier defined, assume 'id'
      return 'id';
    }

    if (primaryId.length === 1) {
      // Simple case: use the single property name directly
      // Note: primaryIdentifier has already been processed by extractPropNames,
      // so it contains plain property names (e.g., ['networkId'])
      return primaryId[0];
    }

    // Composite ID: multiple primary identifiers
    // This indicates an action resource (e.g., subnet with networkId+ipRange)
    return 'physicalId';
  }
}
