import type { IrResourceNode } from '../ir/ir.js';

/**
 * Generates the small, separate source file carrying a Resource's deploy
 * mode (`"synth-only"` vs `"deploy"`) as metadata — deliberately kept out
 * of the Resource's own generated class (see {@link CodeGenerator}), since
 * deploy mode never affects the generated shape, only what a not-yet-built
 * deploy engine does with it afterwards.
 */
export class DeployMetadataGenerator {
  private constructor() {} // no instances — static-only class

  /**
   * Generates the deploy-metadata source file for one Resource.
   *
   * @param resource - the Resource whose deploy mode to emit.
   * @returns the generated TypeScript source, ending in a trailing newline.
   * @example
   * const source = DeployMetadataGenerator.generate(resource);
   */
  public static generate(resource: IrResourceNode): string {
    const key = `${resource.apiVersion}/${resource.resourceType}`;
    return [
      '// AUTO-GENERATED by @cdk-x/generator-toolkit — do not edit by hand.',
      "// Regenerate via the owning library's `generate-l1` Nx target.",
      '',
      'export interface DeployConfig {',
      "  readonly mode: 'synth-only' | 'deploy';",
      '}',
      '',
      'export const DEPLOY_CONFIGS: Record<string, DeployConfig> = {',
      `  '${key}': { mode: '${resource.mode}' },`,
      '};',
      '',
    ].join('\n');
  }
}
