import { Naming } from '../../internal/naming.js';
import type {
  IrComponentNode,
  IrProperty,
  IrPropertyType,
  IrResourceNode,
} from '../ir/ir.js';

type ComponentRefType = Extract<IrPropertyType, { shape: 'component-ref' }>;
type EnumType = Extract<IrPropertyType, { shape: 'enum' }>;

/**
 * Turns IR into generated TypeScript source: one `Resource` subclass for
 * the schema's root, one `Component` subclass per reachable Component.
 * Pure static string-builder — no template engine, matching the pattern of
 * the L1 codegen system's predecessor.
 *
 * Component-typed properties (`shape: 'component-ref'`) never appear in a
 * class's props interface or constructor — children are added as real
 * child constructs (e.g. `new Step(job, 'checkout', {...})`), not passed
 * as data. `toProperties()` inlines them back in by walking
 * `this.node.children`, filtering with `Component.isComponent()` — nothing
 * more specific than that; a Resource/Component with more than one
 * component-ref property isn't supported yet (see
 * {@link CodeGenerator.generate}).
 *
 * Enum-typed properties (`shape: 'enum'`) are emitted as real `export enum`
 * declarations, deduplicated by name across the whole file, and referenced
 * by name wherever used — never inlined as a string-literal union type.
 * jsii doesn't support string-literal unions as a public property type
 * (only interfaces/classes/enums/primitives cross its language targets),
 * so a literal union would fail `jsii-compile` for any jsii-enabled
 * consumer of the generated code.
 */
export class CodeGenerator {
  private constructor() {} // no instances — static-only class

  /**
   * Generates the full source file for one vendored schema's Resource and
   * its Components.
   *
   * @param resource - the schema root's IR.
   * @param components - every Component reachable from `resource`.
   * @returns the generated TypeScript source, ending in a trailing newline.
   * @example
   * const source = CodeGenerator.generate(resource, components);
   */
  public static generate(
    resource: IrResourceNode,
    components: readonly IrComponentNode[],
  ): string {
    const lines: string[] = [
      '// AUTO-GENERATED by @cdk-x/generator-toolkit — do not edit by hand.',
      "// Regenerate via the owning library's `generate-l1` Nx target.",
      '',
      "import { Component, Resource } from '@cdk-x/core';",
      "import { Construct } from 'constructs';",
    ];
    for (const enumType of CodeGenerator.collectEnums([
      resource,
      ...components,
    ])) {
      lines.push('', ...CodeGenerator.enumDeclaration(enumType));
    }
    lines.push('', ...CodeGenerator.resourceClass(resource));
    for (const component of components) {
      lines.push('', ...CodeGenerator.componentClass(component));
    }
    return lines.join('\n') + '\n';
  }

  // jsii doesn't support TypeScript string-literal unions as a public
  // property type (only real interfaces/classes/enums/primitives cross its
  // language targets) — every distinct enum shape gets a single, real
  // `export enum` declaration, deduplicated by name, and every property
  // referencing it points at that declaration by name rather than inlining
  // the union.
  private static collectEnums(
    nodes: readonly { properties: readonly IrProperty[] }[],
  ): EnumType[] {
    const found = new Map<string, EnumType>();
    const visit = (type: IrPropertyType): void => {
      switch (type.shape) {
        case 'enum': {
          const existing = found.get(type.name);
          if (
            existing &&
            !CodeGenerator.sameValues(existing.values, type.values)
          ) {
            throw new Error(
              `Two different enums are both named "${type.name}" ` +
                `(${existing.values.join(', ')} vs ${type.values.join(', ')}) — ` +
                `enum names must be unique across a generated file.`,
            );
          }
          found.set(type.name, type);
          return;
        }
        case 'array':
          return visit(type.items);
        case 'record':
          return visit(type.valueType);
        case 'inline-shape':
          for (const property of type.properties) visit(property.type);
          return;
        default:
          return;
      }
    };
    for (const node of nodes) {
      for (const property of node.properties) visit(property.type);
    }
    return [...found.values()];
  }

  private static sameValues(
    a: readonly string[],
    b: readonly string[],
  ): boolean {
    return (
      a.length === b.length && a.every((value, index) => value === b[index])
    );
  }

  private static enumDeclaration(type: EnumType): string[] {
    return [
      `export enum ${type.name} {`,
      ...type.values.map(
        (value) => `  ${Naming.toPascalCase(value)} = '${value}',`,
      ),
      '}',
    ];
  }

  private static resourceClass(resource: IrResourceNode): string[] {
    const dataProps = CodeGenerator.dataProperties(resource.properties);
    const componentProp = CodeGenerator.soleComponentProperty(
      resource.properties,
    );
    return [
      ...CodeGenerator.propsInterface(
        `${resource.resourceType}Props`,
        dataProps,
      ),
      '',
      ...(resource.description ? [`/**\n * ${resource.description}\n */`] : []),
      `export class ${resource.resourceType} extends Resource {`,
      `  public readonly resourceType = '${resource.resourceType}';`,
      `  public readonly apiVersion = '${resource.apiVersion}';`,
      '',
      ...CodeGenerator.members(dataProps),
      '',
      ...CodeGenerator.constructorLines(
        `${resource.resourceType}Props`,
        dataProps,
      ),
      '',
      ...CodeGenerator.toPropertiesMethod(dataProps, componentProp),
      '}',
    ];
  }

  private static componentClass(component: IrComponentNode): string[] {
    const dataProps = CodeGenerator.dataProperties(component.properties);
    const componentProp = CodeGenerator.soleComponentProperty(
      component.properties,
    );
    return [
      ...CodeGenerator.propsInterface(`${component.name}Props`, dataProps),
      '',
      ...(component.description
        ? [`/**\n * ${component.description}\n */`]
        : []),
      `export class ${component.name} extends Component {`,
      ...CodeGenerator.members(dataProps),
      '',
      ...CodeGenerator.constructorLines(`${component.name}Props`, dataProps),
      '',
      ...CodeGenerator.toPropertiesMethod(dataProps, componentProp),
      '}',
    ];
  }

  private static dataProperties(
    properties: readonly IrProperty[],
  ): IrProperty[] {
    return properties.filter(
      (property) => property.type.shape !== 'component-ref',
    );
  }

  // Only one component-ref property per Resource/Component is supported:
  // toProperties() just filters node.children by Component.isComponent(),
  // with no per-concrete-class discrimination, so there'd be no way to tell
  // two different component-ref properties' children apart if there were
  // more than one.
  private static soleComponentProperty(
    properties: readonly IrProperty[],
  ): (IrProperty & { type: ComponentRefType }) | undefined {
    const componentProps = properties.filter(
      (property): property is IrProperty & { type: ComponentRefType } =>
        property.type.shape === 'component-ref',
    );
    if (componentProps.length > 1) {
      throw new Error(
        `Cannot generate toProperties(): more than one component-ref property ` +
          `(${componentProps.map((property) => property.name).join(', ')}) is not ` +
          `supported yet — only a single nested Component collection per ` +
          `Resource/Component is.`,
      );
    }
    return componentProps[0];
  }

  private static propsInterface(
    name: string,
    properties: readonly IrProperty[],
  ): string[] {
    if (properties.length === 0) {
      return [`export interface ${name} {}`];
    }
    return [
      `export interface ${name} {`,
      ...properties.map(
        (property) =>
          `  readonly ${CodeGenerator.propertyKey(property)}${property.required ? '' : '?'}: ${CodeGenerator.typeToTs(property.type)};`,
      ),
      '}',
    ];
  }

  private static members(properties: readonly IrProperty[]): string[] {
    return properties.map(
      (property) =>
        `  public ${CodeGenerator.memberName(property)}${property.required ? '' : '?'}: ${CodeGenerator.typeToTs(property.type)};`,
    );
  }

  private static constructorLines(
    propsInterfaceName: string,
    properties: readonly IrProperty[],
  ): string[] {
    const hasRequired = properties.some((property) => property.required);
    const propsParam =
      properties.length === 0
        ? ''
        : `, props: ${propsInterfaceName}${hasRequired ? '' : ' = {}'}`;
    return [
      `  constructor(scope: Construct, id: string${propsParam}) {`,
      '    super(scope, id);',
      ...properties.map(
        (property) =>
          `    this.${CodeGenerator.memberName(property)} = ${CodeGenerator.propertyAccessor(property)};`,
      ),
      '  }',
    ];
  }

  private static toPropertiesMethod(
    dataProps: readonly IrProperty[],
    componentProp: (IrProperty & { type: ComponentRefType }) | undefined,
  ): string[] {
    const varName = componentProp
      ? CodeGenerator.memberName(componentProp)
      : '';
    return [
      '  protected toProperties(): Record<string, unknown> {',
      ...(componentProp
        ? CodeGenerator.componentCollectionLines(varName, componentProp.type)
        : []),
      '    return {',
      ...dataProps.map(
        (property) =>
          `      ${CodeGenerator.propertyKey(property)}: this.${CodeGenerator.memberName(property)},`,
      ),
      ...(componentProp
        ? [`      ${CodeGenerator.propertyKey(componentProp)}: ${varName},`]
        : []),
      '    };',
      '  }',
    ];
  }

  private static componentCollectionLines(
    varName: string,
    type: ComponentRefType,
  ): string[] {
    switch (type.collection) {
      case 'array':
        return [
          `    const ${varName} = this.node.children`,
          '      .filter(Component.isComponent)',
          '      .map((child) => child._toProperties());',
        ];
      case 'map':
        return [
          `    const ${varName}: Record<string, unknown> = {};`,
          '    for (const child of this.node.children) {',
          '      if (Component.isComponent(child)) {',
          `        ${varName}[child.node.id] = child._toProperties();`,
          '      }',
          '    }',
        ];
      case 'single':
        return [
          `    const ${varName} = this.node.children.find(Component.isComponent)?._toProperties();`,
        ];
    }
  }

  private static typeToTs(type: IrPropertyType): string {
    switch (type.shape) {
      case 'primitive':
        return type.primitive;
      case 'unknown':
        return 'unknown';
      case 'array': {
        const inner = CodeGenerator.typeToTs(type.items);
        return inner.includes('|') ? `(${inner})[]` : `${inner}[]`;
      }
      case 'record':
        return `Record<string, ${CodeGenerator.typeToTs(type.valueType)}>`;
      case 'enum':
        return type.name;
      case 'component-ref':
        // Never reached: component-ref properties are filtered out of
        // dataProperties() before typeToTs() is ever called on them.
        throw new Error(
          'component-ref properties have no props-interface type',
        );
      case 'inline-shape':
        return `{ ${type.properties
          .map(
            (property) =>
              `readonly ${CodeGenerator.propertyKey(property)}${property.required ? '' : '?'}: ${CodeGenerator.typeToTs(property.type)};`,
          )
          .join(' ')} }`;
    }
  }

  private static propertyKey(property: IrProperty): string {
    return Naming.isValidIdentifier(property.name)
      ? property.name
      : `'${property.name}'`;
  }

  private static memberName(property: IrProperty): string {
    return Naming.isValidIdentifier(property.name)
      ? property.name
      : Naming.toCamelCase(property.name);
  }

  private static propertyAccessor(property: IrProperty): string {
    return Naming.isValidIdentifier(property.name)
      ? `props.${property.name}`
      : `props['${property.name}']`;
  }
}
