// Consolidated release script - version bump, changelog, and "ts"-group
// publish for every project in this workspace, driven by Nx's programmatic
// release API (`releaseVersion`/`releaseChangelog`/`releasePublish` from
// `nx/release`) instead of shelling out to the `nx release` CLI.
//
// Modes (see the dispatch table at the bottom):
//   node tools/release.mjs version    [--projects=<names>] [--first-release] [--dry-run] [--git-commit] [--git-tag]
//   node tools/release.mjs publish-ts [--projects=<names>] [--tag=<npmDistTag>] [--registry=<url>] [--first-release] [--dry-run]
//   node tools/release.mjs list       --group=<jsii|ts> [--projects=<names>]
//
// `version` batches by release PHASE (alpha/beta/rc/stable, read directly
// from each project's phase tag), not by release group: a single call's
// `projects` list can freely mix jsii- and ts-tagged projects together,
// since group membership only matters for *publishing*, not for version/
// changelog mechanics. Batching is required because a single `--preid`
// applies to a whole call, and different projects can be in different
// phases - at most 4 releaseVersion/releaseChangelog call pairs regardless
// of how many libraries exist.
//
// Using the programmatic API (rather than the combined `nx release` CLI
// command) is what lets `gitCommit`/`gitTag` be controlled per call, with no
// nx.json changes anywhere - confirmed live in this repo: releaseVersion
// with gitCommit:false/gitTag:false correctly suppresses git output, and
// releaseChangelog fed that call's own `versionData` result generates the
// changelog with no explicit --version argument and no per-project loop,
// then correctly commits/tags when asked to. This is also what makes the
// local Verdaccio flow (`nx run release-local`) safe: passing no --git-commit/
// --git-tag flags at all defaults both to false, so nothing is ever staged,
// committed, or tagged locally - no cleanup-after-the-fact script needed.
//
// jsii per-language publishing (npm/python/java/dotnet/go) is deliberately
// NOT a mode here - there's no single entry point that fans out per language
// the way releaseVersion/releaseChangelog/releasePublish do for a project
// list, so each language stays a direct `publib-<lang>` invocation (or
// `nx run-many -t jsii-publish-<lang>`) in its own CI job, same as today.
import { execFileSync } from 'node:child_process';
import { releaseChangelog, releasePublish, releaseVersion } from 'nx/release';

// ---- shared helpers (formerly tools/nx-json.mjs and tools/release-phases.mjs) ----

// Runs `nx <args> --json` and parses its output as JSON. Passes --silent to
// pnpm itself (before the nx args): pnpm's own reporter prints a "Scope: all
// N workspace projects" line to stdout ahead of nx's real output whenever it
// decides the invocation spans more than one workspace package - observed on
// fresh CI runners but not reliably on an already-warmed local machine.
// --silent suppresses that reporter unconditionally, so stdout is always
// exactly nx's own JSON.
export function nxJson(args) {
  const stdout = execFileSync('pnpm', ['--silent', 'nx', ...args, '--json'], {
    encoding: 'utf-8',
  });
  return JSON.parse(stdout);
}

// Every publishable project must carry exactly one of these tags in its
// project.json (e.g. "alpha") - the single source of truth for phase, read
// via project tags rather than a custom JSON field, so it can be filtered
// natively with `nx show projects --projects=tag:<X>` instead of requiring a
// per-project JS loop to inspect each project's config.
export const PHASES = ['alpha', 'beta', 'rc', 'stable'];

// Reads the phase out of a project's tags (as returned by `nx show project
// <name> --json`). Defaults to "stable" if no phase tag is present, though
// every project generated by @cdk-x/nx:library or configured by hand should
// always have one explicitly.
export function phaseOf(config) {
  return (config.tags ?? []).find((t) => PHASES.includes(t)) ?? 'stable';
}

// ---- CLI arg parsing ----

function parseArgs(rawArgs) {
  const projectsArg = rawArgs.find((arg) => arg.startsWith('--projects='));
  const tagArg = rawArgs.find((arg) => arg.startsWith('--tag='));
  const groupArg = rawArgs.find((arg) => arg.startsWith('--group='));
  const registryArg = rawArgs.find((arg) => arg.startsWith('--registry='));

  return {
    projectsFilter: projectsArg
      ? projectsArg
          .slice('--projects='.length)
          .split(/[\s,]+/)
          .map((name) => name.trim())
          .filter(Boolean)
      : [],
    tag: tagArg ? tagArg.slice('--tag='.length) : undefined,
    group: groupArg ? groupArg.slice('--group='.length) : undefined,
    registry: registryArg ? registryArg.slice('--registry='.length) : undefined,
    firstRelease: rawArgs.includes('--first-release'),
    dryRun: rawArgs.includes('--dry-run'),
    gitCommit: rawArgs.includes('--git-commit'),
    gitTag: rawArgs.includes('--git-tag'),
  };
}

function matchesFilter(project, projectsFilter) {
  return projectsFilter.length === 0 || projectsFilter.includes(project);
}

// ---- modes ----

// Bumps every publishable project's version and generates its changelog
// entry, batched by release phase. Returns the list of projects that
// actually received a real version bump this run (derived directly from
// releaseVersion's own returned versionData, not from `git show --affected`
// or a git tag diff - both of which break once this script starts
// committing directly to a release branch: `--affected` resolves via
// `git merge-base(base, head)`, and once a commit lands ON main/next itself,
// merge-base(branch, HEAD) === HEAD, so the diff would silently be empty).
export async function version({
  projectsFilter = [],
  firstRelease = false,
  dryRun = false,
  gitCommit = false,
  gitTag = false,
} = {}) {
  const releasedProjects = [];

  for (const phase of PHASES) {
    const phaseProjects = nxJson([
      'show',
      'projects',
      '--with-target',
      'nx-release-publish',
      `--projects=tag:${phase}`,
    ]).filter((project) => matchesFilter(project, projectsFilter));

    if (phaseProjects.length === 0) {
      continue;
    }

    const specifier = firstRelease
      ? phase === 'stable'
        ? '1.0.0'
        : `1.0.0-${phase}.0`
      : undefined;
    const preid = !firstRelease && phase !== 'stable' ? phase : undefined;

    const { projectsVersionData, releaseGraph } = await releaseVersion({
      projects: phaseProjects,
      specifier,
      preid,
      firstRelease,
      dryRun,
      gitCommit: false,
      gitTag: false,
      // Version/changelog steps stage their changes with git even when not
      // committing, unless told not to - only stage when we're about to
      // commit right after, so the local Verdaccio flow never leaves
      // anything in the index.
      stageChanges: gitCommit,
    });

    await releaseChangelog({
      projects: phaseProjects,
      versionData: projectsVersionData,
      releaseGraph,
      firstRelease,
      dryRun,
      gitCommit,
      gitTag,
      gitPush: false,
      stageChanges: gitCommit,
    });

    for (const [project, data] of Object.entries(projectsVersionData)) {
      if (data.newVersion && data.newVersion !== data.currentVersion) {
        releasedProjects.push(project);
      }
    }
  }

  return releasedProjects;
}

// Publishes every "ts" (non-jsii, ordinary TypeScript) project via Nx's own
// default nx-release-publish executor - unlike jsii projects, ts packages
// have exactly one publish target (npm), so releasePublish's normal
// per-project fan-out is all that's needed here, no per-language batching.
export async function publishTs({
  projectsFilter = [],
  tag,
  registry,
  firstRelease = false,
  dryRun = false,
} = {}) {
  const tsProjects = nxJson([
    'show',
    'projects',
    '--with-target',
    'nx-release-publish',
    '--projects=tag:ts',
  ]).filter((project) => matchesFilter(project, projectsFilter));

  if (tsProjects.length === 0) {
    console.log('No ts projects to publish.');
    return;
  }

  await releasePublish({
    projects: tsProjects,
    tag,
    registry,
    firstRelease,
    dryRun,
  });
}

// Lists every publishable project in the given release group (name, root,
// phase) as a JSON array - feeds CI's per-language/per-package publish job
// matrices without ever hardcoding a package list in the workflow YAML.
// `phase` drives the npm dist-tag: "stable" publishes under npm's default
// "latest" tag, anything else must publish under its own phase tag so a
// prerelease never becomes what `npm install <pkg>` resolves to.
export function list({ group, projectsFilter = [] } = {}) {
  if (group !== 'jsii' && group !== 'ts') {
    throw new Error(`--group must be "jsii" or "ts", got: ${group}`);
  }

  const projects = nxJson([
    'show',
    'projects',
    '--with-target',
    'nx-release-publish',
    `--projects=tag:${group}`,
  ]).filter((project) => matchesFilter(project, projectsFilter));

  return projects.map((project) => {
    const config = nxJson(['show', 'project', project]);
    return {
      project,
      name: config.root.split('/').pop(),
      root: config.root,
      phase: phaseOf(config),
    };
  });
}

// ---- CLI dispatch (only runs when this file is executed directly, not when
// its exports are imported by e.g. tools/validate-release-phase.mjs) ----

const isMain = import.meta.url === `file://${process.argv[1]}`;

if (isMain) {
  const [mode, ...rawArgs] = process.argv.slice(2);
  const args = parseArgs(rawArgs);

  switch (mode) {
    case 'version': {
      const releasedProjects = await version(args);
      // Comma-separated, matching the --projects= format every other mode
      // (and the workflow_dispatch `projects` input) already expects - this
      // is meant to be piped straight into `list`/`publish-ts`'s
      // --projects= filter, not parsed as JSON.
      console.log(releasedProjects.join(','));
      break;
    }
    case 'publish-ts': {
      await publishTs(args);
      break;
    }
    case 'list': {
      const result = list(args);
      process.stdout.write(JSON.stringify(result));
      break;
    }
    default: {
      console.error(
        'Usage: node tools/release.mjs <version|publish-ts|list> [options]',
      );
      process.exit(1);
    }
  }
}
