// The fixed, small set of release phases a project can be in. Every
// publishable project must carry exactly one "phase-<X>" tag in its
// project.json (e.g. "phase-alpha") - this is the single source of truth for
// phase, read via project tags rather than a custom JSON field, so it can be
// filtered natively with `nx show projects --projects=tag:phase-<X>` /
// `-p tag:phase-<X>` instead of requiring a per-project JS loop to inspect
// each project's config individually.
export const PHASES = ['alpha', 'beta', 'rc', 'stable'];

// Reads the phase out of a project's tags (as returned by `nx show project
// <name> --json`). Defaults to "stable" if no phase-* tag is present, though
// every project generated by @cdk-x/nx:library or configured by hand should
// always have one explicitly.
export function phaseOf(config) {
  const tag = (config.tags ?? []).find((t) => t.startsWith('phase-'));
  return tag ? tag.slice('phase-'.length) : 'stable';
}
